# Generated by Django 3.2.9 on 2022-04-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'База рассылки'},
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.TextField(default='new', verbose_name='Статус клиента'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
