# Generated by Django 3.2.9 on 2022-04-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_auto_20220414_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
